### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MMKrell** [rock-learning/bolero#1]
You should upload a pregenerated documentation webpage on guthub (gh-pages) and put a link into the README file.

**Comment by AlexanderFabisch** [comment]
Thanks, this will be done soon!

**Comment by AlexanderFabisch** [comment]
The documentation is available now [here](https://rock-learning.github.io/bolero/). Close this issue if you think it is fixed.

**Comment by MMKrell** [comment]
Perfect. That was fast!
