### ISSUE TITLE
can't find cart_dmp_config.yaml and cart_dmp_model.yaml in the example python scripts

### ISSUE THREAD

**Issue by ChenEating716** [rock-learning/bolero#121]
Dear Developers,

I met this problem when I tried to test the DMP example python scripts.
I guess there might be some file missing.

FileNotFoundError: [Errno 2] No such file or directory: '/home/XXX/Documents/BOLeRo/auto_examples_python/representation/cart_dmp_model.yaml'

**Comment by AlexanderFabisch** [comment]
Hi @ChenEating716 

I guess you want to run this example: https://github.com/rock-learning/bolero/blob/master/examples/representation/plot_cartesian_dmp.py

It is trying to load this file: https://github.com/rock-learning/bolero/blob/master/examples/representation/cart_dmp_model.yaml

In this line: https://github.com/rock-learning/bolero/blob/master/examples/representation/plot_cartesian_dmp.py#L69

Your path (`/home/XXX/Documents/BOLeRo/auto_examples_python`) indicates that you are trying to run the script that has been included in the API documentation. There will be no such configuration file. Try the run the script that is located in the examples folder instead.

**Comment by ChenEating716** [comment]
Hi @AlexanderFabisch 

Thanks for the quick reply !

I downloaded the example scripts from https://rock-learning.github.io/bolero/auto_examples/index.html, I think that's why I missed the .yaml file.
