### ISSUE TITLE
Defining simulation parameters via learning_config fails

### ISSUE THREAD

**Issue by hwiedDFKI** [rock-learning/bolero#49]
While MARSEnvironmentHelper::init() tries to hand calc_ms to mars, if(marsPlugin->control->cfg) results in segementation fault. (master)

**Comment by AlexanderFabisch** [comment]
Can you give me a configuration file that can be used to reproduce this bug?

**Comment by AlexanderFabisch** [comment]
There is a merge request: #50 

Could you check if that works for you? I would clean it up and push it to master then.

**Comment by hwiedDFKI** [comment]
Unfortunately it doesn't.

**Comment by AlexanderFabisch** [comment]
I have problems with the reproduction of this error. @malter It would be good if you could take a look when you are back.

**Comment by AlexanderFabisch** [comment]
Hotfix: use [release 0.2](https://github.com/rock-learning/bolero/releases/tag/v0.2.0)

**Comment by hwiedDFKI** [comment]
Fixed by pull request #48

**Comment by AlexanderFabisch** [comment]
It is usually better to split it up into two pull requests.

**Comment by AlexanderFabisch** [comment]
You can close the issue if you think the problem is solved.
