### ISSUE TITLE
build error with dmp

### ISSUE THREAD

**Issue by zjxiaobai** [rock-learning/bolero#51]
when I run ./bootstrap_bolero.sh to install bolero, it went into error while building dmp.

Sine it did not print the reason why this failed, I can't do anything to fix this.

Below is what it looks like:

Install: ['learning/bolero/bolero/wrapper', 'learning/bolero/src/controller', 'learning/bolero/src/representation/dmp']
learning/bolero/src/controller configured
learning/bolero/bolero/wrapper configured
learning/bolero/bolero/wrapper installed
learning/bolero/src/representation/dmp configured
learning/bolero/src/controller installed
learning/bolero/src/representation/dmp build error
Install: ['learning/bolero']
learning/bolero configured
learning/bolero build error

Errors:
 - build: learning/bolero/src/representation/dmp
 - build: learning/bolero

**Comment by AlexanderFabisch** [comment]
I assume Cython is not correctly installed or is too old. What is your OS? What is your Cython vesion (`cython --version`)?

Could you go to `bolero-dev/learning/bolero/src/representation/dmp/build/` and run `make install`? What is the error message?

**Comment by zjxiaobai** [comment]
Oh,I'm sorry,I should have stated my environment more clear before, my os is ubuntu 16.04 and the cython is 0.27.3, and I'm doing all this under anaconda environment.

The error message shown after make install is 

[  5%] Built target dmp
Traceback (most recent call last):
  File "/home/zj/Documents/bolero-dev/learning/bolero/src/representation/dmp/implementation/dmp/setup.py", line 4, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
implementation/dmp/CMakeFiles/python_setup.dir/build.make:61: recipe for target 'python_setup' failed
make[2]: *** [python_setup] Error 1
CMakeFiles/Makefile2:161: recipe for target 'implementation/dmp/CMakeFiles/python_setup.dir/all' failed
make[1]: *** [implementation/dmp/CMakeFiles/python_setup.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zjxiaobai** [comment]
After following the error message, I reinstall cython and install numpy, I successfully install bolero with dmp, thank you very much !

**Comment by AlexanderFabisch** [comment]
Strange error... 

> After following the error message, I reinstall cython and install numpy, I successfully install bolero with dmp, thank you very much !

You are welcome.
