### ISSUE TITLE
Inconsitency in dmp_sequence.py

### ISSUE THREAD

**Issue by ChristophPetzoldt** [rock-learning/bolero#52]
In the parameter description of the class DMPSequence, it is specified: 
```
    initial_weights : list
        List of initial weight vectors for the DMPs
```

https://github.com/rock-learning/bolero/blob/229f447611ddfddd9ec413fcc2142aa84a820104/bolero/representation/dmp_sequence.py#L36

However, if initial_weights is set as a normal list, w.reshape would be called on an integer in line 109, which throws an AttributeError:
 ```
 self.weights = [w.reshape(self.n_weights_per_dmp[i],
                                      self.n_task_dims)
                            for w in self.initial_weights]
```
https://github.com/rock-learning/bolero/blob/229f447611ddfddd9ec413fcc2142aa84a820104/bolero/representation/dmp_sequence.py#L109

**Comment by AlexanderFabisch** [comment]
Technically, that is not an error. `initial_weights` can be a list if all elements are arrays. :)

This is certainly not the best documentation though. What about

```
 self.weights = [np.asarray(w).reshape(self.n_weights_per_dmp[i],  ...
```

?

I would also change to the documentation to

```
    initial_weights : array-like
```

**Comment by ChristophPetzoldt** [comment]
We could also specify the required length of the array (sum(self.n_features) * self.n_task_dims) in the documentation.
Changing the code as suggested looks good to me.

**Comment by AlexanderFabisch** [comment]
Ah, wait a second, that is exactly the problem. The individual DMPs can have different numbers of weights. That is the reason why it is usually not an array. Each entry `initial_weights[i]` has the shape `self.n_features[i] * self.n_task_dims`.

**Comment by ChristophPetzoldt** [comment]
Ahh yes, you're right! So we leave the code as it is. However, you might extend the documentation with "Each entry has the shape of n_features[i] * n_task_dims" to make the initialization more transparent.

**Comment by AlexanderFabisch** [comment]
Could you make a pull request? I don't know when I will have the time...

**Comment by ChristophPetzoldt** [comment]
I created the pull request #61 .
