### ISSUE TITLE
Missing dependencies for mars_environment

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-learning/bolero#8]
@HWiese1980 told me that mars_environment depends on

* simulation/mars/entity_generation/smurf
* simulation/mars/smurf_loader

Both are not listed in the [manifest.xml](https://github.com/rock-learning/bolero/blob/master/src/environment/mars_environment/manifest.xml). Should we add them? @malter

**Comment by malter** [comment]
mars_environment tries to load the libraries on runtime but it also runs without that libraries. Additionally, there is no build dependency. However, I will add them as optional dependency to the simulation/mars/app package with the next merge from "develop -> master".

**Comment by AlexanderFabisch** [comment]
Good. I will leave this issue open.
