### ISSUE TITLE
Reloading DMPs produces wrong trajectories after re-execution

### ISSUE THREAD

**Issue by ChristophPetzoldt** [rock-learning/bolero#83]
Loading an previously saved DMP model and executing the represented trajectory fails for some trajectories. 
See test case with example trajectory in commit [e18402b8e4d9b9d71aae7a7bf8e77c6d41b639b5](https://github.com/ChristophPetzoldt/bolero/commit/e18402b8e4d9b9d71aae7a7bf8e77c6d41b639b5) in forked repository. 
While an synthetic sinus trajectory is correctly loaded, loading and executing non-synthetic trajectories produces bad results.

There must be an issue at C++ side as all the variables on python side are correctly loaded and identical. 
The acceleration ydd quickly becomes quite large at the beginning of the trajectory execution.

**Comment by AlexanderFabisch** [comment]
Minimal example to reproduce this bug:

```python
import numpy as np
import matplotlib.pyplot as plt
from bolero.representation import DMPBehavior

random_state = np.random.RandomState(0)

dmp = DMPBehavior(execution_time=1.0, dt=0.001)
dmp.init(6, 6)
x0 = np.zeros(2)
g = np.ones(2)
dmp.set_meta_parameters(["x0", "g"], [x0, g])
w = dmp.get_params()
w = random_state.randn(*w.shape) * 1000.0
dmp.set_params(w)

Y, Yd, Ydd = dmp.trajectory()

dmp.save("test_model.yaml")
dmp.save_config("test_config.yaml")

dmp = DMPBehavior(configuration_file="test_model.yaml")
dmp.init(6, 6)
dmp.load_config("test_config.yaml")

Y2, Yd2, Ydd2 = dmp.trajectory()

plt.figure()
plt.plot(Y[:, 0], color="k")
plt.plot(Y[:, 1], color="k")
plt.plot(Y2[:, 0], color="r")
plt.plot(Y2[:, 1], color="r")
plt.show()
```

**Comment by AlexanderFabisch** [comment]
As a workaround: pickle works perfectly fine with DMPBehavior and CartesianDMPBehavior.
